// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('AdminCreateAndDeleteUser', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AdminCreateAndDeleteUser', async function() {
    await driver.get("http://localhost:9000/")
    await driver.manage().window().setRect(945, 1031)
    await driver.findElement(By.css(".dropdown-toggle > span")).click()
    await driver.findElement(By.css("#login-item > span")).click()
    await driver.findElement(By.id("username")).sendKeys("admin")
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.css(".btn-primary > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("#admin-menu > .d-flex > span")).click()
    await driver.findElement(By.css(".show > .dropdown-item:nth-child(1) > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".float-right > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys("test1")
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("test1")
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("test1")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("test1@mail.com")
    {
      const dropdown = await driver.findElement(By.id("authorities"))
      await dropdown.findElement(By.xpath("//option[. = 'ROLE_USER']")).click()
    }
    await driver.findElement(By.css(".btn-primary > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("#test1 .btn-danger > .svg-inline--fa")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".btn-danger:nth-child(2) > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    {
      const elements = await driver.findElements(By.css(".Toastify__toast-body"))
      assert(elements.length)
    }
  })
})
