///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PerformanceRatingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4ad710aa-0bc8-49c0-a173-0c8437591ece")]
    public partial class PerformanceRatingRepository : RepoGenBaseFolder
    {
        static PerformanceRatingRepository instance = new PerformanceRatingRepository();
        PerformanceRatingRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        PerformanceRatingRepositoryFolders.GoogleGoogleChromeAppFolder _googlegooglechrome;
        PerformanceRatingRepositoryFolders.GoogleAppFolder _google;
        PerformanceRatingRepositoryFolders.PerformanceRatingAppFolder _performancerating;
        PerformanceRatingRepositoryFolders.PerformanceRatingGoogleChromeAppFolder _performanceratinggooglechrome;
        PerformanceRatingRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the PerformanceRatingRepository element repository.
        /// </summary>
        [RepositoryFolder("4ad710aa-0bc8-49c0-a173-0c8437591ece")]
        public static PerformanceRatingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PerformanceRatingRepository() 
            : base("PerformanceRatingRepository", "/", null, 0, false, "4ad710aa-0bc8-49c0-a173-0c8437591ece", ".\\RepositoryImages\\PerformanceRatingRepository4ad710aa.rximgres")
        {
            _applicationundertest = new PerformanceRatingRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _googlegooglechrome = new PerformanceRatingRepositoryFolders.GoogleGoogleChromeAppFolder(this);
            _google = new PerformanceRatingRepositoryFolders.GoogleAppFolder(this);
            _performancerating = new PerformanceRatingRepositoryFolders.PerformanceRatingAppFolder(this);
            _performanceratinggooglechrome = new PerformanceRatingRepositoryFolders.PerformanceRatingGoogleChromeAppFolder(this);
            _explorer = new PerformanceRatingRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4ad710aa-0bc8-49c0-a173-0c8437591ece")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("0f9b6700-dbd3-4830-a2ef-033ff14cd79f")]
        public virtual PerformanceRatingRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The GoogleGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("9ccc252d-98f1-4ad1-8d86-4e01c604a4fd")]
        public virtual PerformanceRatingRepositoryFolders.GoogleGoogleChromeAppFolder GoogleGoogleChrome
        {
            get { return _googlegooglechrome; }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("cbceb8bf-5193-48e6-ae67-8959243f2699")]
        public virtual PerformanceRatingRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }

        /// <summary>
        /// The PerformanceRating folder.
        /// </summary>
        [RepositoryFolder("b9f46552-56c2-4da2-93db-6687b04d3df8")]
        public virtual PerformanceRatingRepositoryFolders.PerformanceRatingAppFolder PerformanceRating
        {
            get { return _performancerating; }
        }

        /// <summary>
        /// The PerformanceRatingGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("0ae15e82-60b5-4fac-9011-219a41e3dbd3")]
        public virtual PerformanceRatingRepositoryFolders.PerformanceRatingGoogleChromeAppFolder PerformanceRatingGoogleChrome
        {
            get { return _performanceratinggooglechrome; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("864e7185-a511-45ab-a104-5a7dcb3b633d")]
        public virtual PerformanceRatingRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PerformanceRatingRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("0f9b6700-dbd3-4830-a2ef-033ff14cd79f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='http://192.168.178.58:9000/']", parentFolder, 30000, null, false, "0f9b6700-dbd3-4830-a2ef-033ff14cd79f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0f9b6700-dbd3-4830-a2ef-033ff14cd79f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0f9b6700-dbd3-4830-a2ef-033ff14cd79f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("9ccc252d-98f1-4ad1-8d86-4e01c604a4fd")]
        public partial class GoogleGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _adressundsuchleisteInfo;
            RepoItemInfo _paneInfo;
            RepoItemInfo _pane1Info;
            RepoItemInfo _groupingInfo;

            /// <summary>
            /// Creates a new GoogleGoogleChrome  folder.
            /// </summary>
            public GoogleGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GoogleGoogleChrome", "/form[@title='Google - Google Chrome']", parentFolder, 30000, null, true, "9ccc252d-98f1-4ad1-8d86-4e01c604a4fd", "")
            {
                _adressundsuchleisteInfo = new RepoItemInfo(this, "AdressUndSuchleiste", "container[@accessiblename='Google - Google Chrome']/container[@accessiblename='Google Chrome']//container[@accessiblerole='Grouping']/text[@accessiblename='Adress- und Suchleiste']", 30000, null, "c4f157f1-952d-4212-8216-7bac253957f6");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename='Google - Google Chrome']/container[@accessiblename='']/container/container[@accessiblerole='Pane']/container[@accessiblerole='Pane']", 30000, null, "0f28b76d-b83b-4422-8cba-cffc94e9d070");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename='Google - Google Chrome']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[2]", 30000, null, "b22bd299-9f3b-40f6-b7a3-3149a1e5d926");
                _groupingInfo = new RepoItemInfo(this, "Grouping", "container[@accessiblename='Google - Google Chrome']/container[@accessiblename='Google Chrome']//container[@accessiblerole='Grouping']", 30000, null, "6c9efd2e-3abc-40e3-924a-82018d95b2a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9ccc252d-98f1-4ad1-8d86-4e01c604a4fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ccc252d-98f1-4ad1-8d86-4e01c604a4fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AdressUndSuchleiste item.
            /// </summary>
            [RepositoryItem("c4f157f1-952d-4212-8216-7bac253957f6")]
            public virtual Ranorex.Text AdressUndSuchleiste
            {
                get
                {
                    return _adressundsuchleisteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AdressUndSuchleiste item info.
            /// </summary>
            [RepositoryItemInfo("c4f157f1-952d-4212-8216-7bac253957f6")]
            public virtual RepoItemInfo AdressUndSuchleisteInfo
            {
                get
                {
                    return _adressundsuchleisteInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("0f28b76d-b83b-4422-8cba-cffc94e9d070")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("0f28b76d-b83b-4422-8cba-cffc94e9d070")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("b22bd299-9f3b-40f6-b7a3-3149a1e5d926")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("b22bd299-9f3b-40f6-b7a3-3149a1e5d926")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("6c9efd2e-3abc-40e3-924a-82018d95b2a9")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("6c9efd2e-3abc-40e3-924a-82018d95b2a9")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("cbceb8bf-5193-48e6-ae67-8959243f2699")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _n1xjcfne6nsdo3j99Info;
            RepoItemInfo _divtaggbInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "cbceb8bf-5193-48e6-ae67-8959243f2699", "")
            {
                _n1xjcfne6nsdo3j99Info = new RepoItemInfo(this, "N1xJcfNe6nSdO3j99", "body/div[1]/div[1]", 30000, null, "5292608b-81a0-4bd2-b267-91ca697ac560");
                _divtaggbInfo = new RepoItemInfo(this, "DivTagGb", ".//div[#'gb']", 30000, null, "c52ed09a-37fd-4b44-aa99-62e9e8984741");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cbceb8bf-5193-48e6-ae67-8959243f2699")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cbceb8bf-5193-48e6-ae67-8959243f2699")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The N1xJcfNe6nSdO3j99 item.
            /// </summary>
            [RepositoryItem("5292608b-81a0-4bd2-b267-91ca697ac560")]
            public virtual Ranorex.DivTag N1xJcfNe6nSdO3j99
            {
                get
                {
                    return _n1xjcfne6nsdo3j99Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The N1xJcfNe6nSdO3j99 item info.
            /// </summary>
            [RepositoryItemInfo("5292608b-81a0-4bd2-b267-91ca697ac560")]
            public virtual RepoItemInfo N1xJcfNe6nSdO3j99Info
            {
                get
                {
                    return _n1xjcfne6nsdo3j99Info;
                }
            }

            /// <summary>
            /// The DivTagGb item.
            /// </summary>
            [RepositoryItem("c52ed09a-37fd-4b44-aa99-62e9e8984741")]
            public virtual Ranorex.DivTag DivTagGb
            {
                get
                {
                    return _divtaggbInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagGb item info.
            /// </summary>
            [RepositoryItemInfo("c52ed09a-37fd-4b44-aa99-62e9e8984741")]
            public virtual RepoItemInfo DivTagGbInfo
            {
                get
                {
                    return _divtaggbInfo;
                }
            }
        }

        /// <summary>
        /// The PerformanceRatingAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9f46552-56c2-4da2-93db-6687b04d3df8")]
        public partial class PerformanceRatingAppFolder : RepoGenBaseFolder
        {
            PerformanceRatingRepositoryFolders.OperationsAccountResourceIsAuthenticaFolder _operationsaccountresourceisauthentica;
            RepoItemInfo _signinInfo;
            RepoItemInfo _signin1Info;
            RepoItemInfo _http192168178589000hashInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _btnbtnprimaryInfo;
            RepoItemInfo _alertalertsuccessfadeshowInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _registerInfo;
            RepoItemInfo _register1Info;
            RepoItemInfo _toastifytoastbodyInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _secondpasswordInfo;
            RepoItemInfo _spantagpleasecheckyouremailforconfInfo;
            RepoItemInfo _accountInfo;
            RepoItemInfo _firstpasswordInfo;
            RepoItemInfo _registersubmitInfo;
            RepoItemInfo _loginitemInfo;
            RepoItemInfo _settingsInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _btnbtnprimary1Info;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _http192168178589000accountsettiInfo;
            RepoItemInfo _http192168178589000accountpasswInfo;
            RepoItemInfo _currentpasswordInfo;
            RepoItemInfo _newpasswordInfo;
            RepoItemInfo _confirmpasswordInfo;
            RepoItemInfo _btnbtnsuccessInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _somespantagInfo;
            RepoItemInfo _password1Info;
            RepoItemInfo _http192168178589000hash1Info;
            RepoItemInfo _http192168178589000adminusermaInfo;
            RepoItemInfo _createanewuserInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _roleuserInfo;
            RepoItemInfo _save1Info;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _delete1Info;
            RepoItemInfo _administrationInfo;
            RepoItemInfo _usermanagementInfo;
            RepoItemInfo _viewInfo;
            RepoItemInfo _backInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _btnbtnprimary2Info;
            RepoItemInfo _http192168178589000admindocsInfo;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _http192168178589000h2consoleInfo;

            /// <summary>
            /// Creates a new PerformanceRating  folder.
            /// </summary>
            public PerformanceRatingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PerformanceRating", "/dom[@domain='192.168.178.58:9000']", parentFolder, 30000, null, false, "b9f46552-56c2-4da2-93db-6687b04d3df8", "")
            {
                _operationsaccountresourceisauthentica = new PerformanceRatingRepositoryFolders.OperationsAccountResourceIsAuthenticaFolder(this);
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//a[#'login-item']/span[@innertext='Sign in']", 30000, null, "ab1d6f40-d693-4489-8a42-aedfe7e5baf7");
                _signin1Info = new RepoItemInfo(this, "SignIn1", ".//div[#'login-page']/?/?/form[@action='http://192.168.178.58:9000/#']/div[3]/button[2]/span[@innertext='Sign in']", 30000, null, "336f9d5a-0b1a-4da9-bb5b-71167a936423");
                _http192168178589000hashInfo = new RepoItemInfo(this, "Http192168178589000Hash", ".//li[#'account-menu']/a[@href>'http://192.168.178.58:900']", 30000, null, "4ee167e1-c819-4a66-a6fe-84ff6865f41f");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "d57cdec9-7d51-4047-93ff-62aea8d4ef59");
                _btnbtnprimaryInfo = new RepoItemInfo(this, "BtnBtnPrimary", ".//div[#'login-page']/?/?/form[@action='http://192.168.178.58:9000/#']/div[3]/button[2]", 30000, null, "f99133cb-fba0-405a-9dc5-e9a58948c1ec");
                _alertalertsuccessfadeshowInfo = new RepoItemInfo(this, "AlertAlertSuccessFadeShow", ".//div[#'app-view-container']/div[1]/div/div/div[1]/div/div", 30000, null, "6ad9825c-3f4e-454f-8ef7-13356c086be4");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "613d6c04-1432-4a11-9b27-491480995bde");
                _registerInfo = new RepoItemInfo(this, "Register", ".//li[#'account-menu']//span[@innertext='Register']", 30000, null, "8fae3609-9492-48cf-aa07-8917bbd6fd66");
                _register1Info = new RepoItemInfo(this, "Register1", ".//button[#'register-submit']/span[@innertext='Register']", 30000, null, "a32bd765-028a-45b3-b7ef-b2177d1160b3");
                _toastifytoastbodyInfo = new RepoItemInfo(this, "ToastifyToastBody", ".//div[#'root']/div/div[2]/div[1]/div/div/div[1]", 30000, null, "6078dc83-0369-4741-834f-2aa4d9c85b77");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "a8feeaa2-da9e-4868-8f26-d31e21c66235");
                _secondpasswordInfo = new RepoItemInfo(this, "SecondPassword", ".//input[#'secondPassword']", 30000, null, "b22840fd-5069-4b6e-9615-d234454d4fb4");
                _spantagpleasecheckyouremailforconfInfo = new RepoItemInfo(this, "SpanTagPleaseCheckYourEmailForConf", ".//div[#'root']/div/div[2]/div[1]/div/div/div[1]/span[@innertext>' Please check your email for']", 30000, null, "74055951-5198-43ad-8ce3-9f74d4df8a3d");
                _accountInfo = new RepoItemInfo(this, "Account", ".//li[#'account-menu']/?/?/span[@innertext='Account']", 30000, null, "ae449e60-cbd1-418e-a9ee-7c10ecb6af00");
                _firstpasswordInfo = new RepoItemInfo(this, "FirstPassword", ".//input[#'firstPassword']", 30000, null, "7fc91c0d-8ad2-4525-a2cc-3bf09fc3bc51");
                _registersubmitInfo = new RepoItemInfo(this, "RegisterSubmit", ".//button[#'register-submit']", 30000, null, "ebb00c23-7048-4248-9374-dec251df4184");
                _loginitemInfo = new RepoItemInfo(this, "LoginItem", ".//a[#'login-item']", 30000, null, "49d571a7-49c3-4eff-84d8-d9d6541532a3");
                _settingsInfo = new RepoItemInfo(this, "Settings", ".//li[#'account-menu']//span[@innertext='Settings']", 30000, null, "71ce774c-53af-4e69-b139-e36356930e7f");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'firstName']", 30000, null, "f111b160-075a-4335-a363-68770df90664");
                _btnbtnprimary1Info = new RepoItemInfo(this, "BtnBtnPrimary1", ".//form[#'settings-form']/button", 30000, null, "26906082-4f7a-4cf2-974d-9a19dc228da5");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'lastName']", 30000, null, "50943198-4f91-4256-8031-6311c4574f56");
                _http192168178589000accountsettiInfo = new RepoItemInfo(this, "Http192168178589000AccountSetti", ".//li[#'account-menu']/div/a[1]", 30000, null, "f103ffc2-9035-4717-8f8d-5f5eabe93368");
                _http192168178589000accountpasswInfo = new RepoItemInfo(this, "Http192168178589000AccountPassw", ".//li[#'account-menu']/div/a[2]", 30000, null, "637afc29-f373-40a2-9466-77ec3c3de201");
                _currentpasswordInfo = new RepoItemInfo(this, "CurrentPassword", ".//input[#'currentPassword']", 30000, null, "4113adcd-5d2f-4db8-970f-2025a7376a4f");
                _newpasswordInfo = new RepoItemInfo(this, "NewPassword", ".//input[#'newPassword']", 30000, null, "15c7dfe2-a3ff-456b-9dbb-137fedc64722");
                _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", ".//input[#'confirmPassword']", 30000, null, "206baca1-e2ea-4dac-b2e0-41d8b4f50ceb");
                _btnbtnsuccessInfo = new RepoItemInfo(this, "BtnBtnSuccess", ".//form[#'password-form']/button", 30000, null, "e9f2db67-1cbe-4198-a35e-4821a01ddc44");
                _saveInfo = new RepoItemInfo(this, "Save", ".//form[#'password-form']/?/?/span[@innertext='Save']", 30000, null, "61fe6c89-abc9-47d9-9441-bf30c1b683ab");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", ".//div[#'login-title']/?/?/span[@innertext='×']", 30000, null, "3e575f67-e73d-49ee-8b86-fc22c318d9cf");
                _password1Info = new RepoItemInfo(this, "Password1", ".//li[#'account-menu']//span[@innertext='Password']", 30000, null, "4e66dd21-fe6e-4145-8907-a96ceeea9605");
                _http192168178589000hash1Info = new RepoItemInfo(this, "Http192168178589000Hash1", ".//li[#'admin-menu']/a[@href>'http://192.168.178.58:900']", 30000, null, "286e6589-9b22-4724-801e-920de9a22171");
                _http192168178589000adminusermaInfo = new RepoItemInfo(this, "Http192168178589000AdminUserMa", ".//li[#'admin-menu']/div/a[1]", 30000, null, "948fe97d-ddec-4a93-a48f-7531e85c483e");
                _createanewuserInfo = new RepoItemInfo(this, "CreateANewUser", ".//h2[#'user-management-page-heading']/?/?/span[@innertext='Create a new user']", 30000, null, "2d0d78c2-555f-4edb-b54c-6c79ab348d15");
                _loginInfo = new RepoItemInfo(this, "Login", ".//input[#'login']", 30000, null, "d4a6f2b2-3884-49f6-ab52-41246b1c5af7");
                _roleuserInfo = new RepoItemInfo(this, "ROLEUSER", ".//select[#'authorities']/option[@value='ROLE_USER']", 30000, null, "f3e92086-04de-44dd-b488-aa9dbfaa6115");
                _save1Info = new RepoItemInfo(this, "Save1", ".//div[#'app-view-container']/div[1]//form[@action='http://192.168.178.58:9000/#']/button/span[@innertext='Save']", 30000, null, "d12c1bcf-5be1-4fc9-a800-d735f2de612d");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//tr[#'usertest']/td[10]//span[@innertext='Delete']", 30000, null, "f0eb9458-b2d0-4280-8ed8-b646b0c9f8ec");
                _delete1Info = new RepoItemInfo(this, "Delete1", "body/div[2]/div/div[1]/div/div/div[3]/?/?/span[@innertext='Delete']", 30000, null, "520c85ef-8372-46d0-95f8-ace692dc6fc6");
                _administrationInfo = new RepoItemInfo(this, "Administration", ".//li[#'admin-menu']/?/?/span[@innertext='Administration']", 30000, null, "e74f0e29-8c91-4909-86fb-f2efffd2a029");
                _usermanagementInfo = new RepoItemInfo(this, "UserManagement", ".//li[#'admin-menu']//span[@innertext='User management']", 30000, null, "fe80d8ce-bb0a-4913-a8c4-775a60019f84");
                _viewInfo = new RepoItemInfo(this, "View", ".//div[#'app-view-container']/div[1]/div/div/div/div[1]/table/tbody/tr[3]/td[10]/div/a[1]/?/?/span[@innertext='View']", 30000, null, "e96853f8-6335-4b31-a31f-a2dbbcafa060");
                _backInfo = new RepoItemInfo(this, "Back", ".//div[#'app-view-container']/div[1]//a[@href>'http://192.168.178.58:900']/?/?/span[@innertext='Back']", 30000, null, "790f08a8-387c-4254-a1b8-3e3307a28ae8");
                _editInfo = new RepoItemInfo(this, "Edit", ".//div[#'app-view-container']/div[1]/div/div/div/div[1]/table/tbody/tr[3]/td[10]/div/a[2]/?/?/span[@innertext='Edit']", 30000, null, "edc0f65c-b78d-4e3a-b9c5-f7a8b46eee94");
                _btnbtnprimary2Info = new RepoItemInfo(this, "BtnBtnPrimary2", ".//div[#'app-view-container']/div[1]/div/div/div/div[2]/?/?/form[@action='http://192.168.178.58:9000/#']/button", 30000, null, "270ba79e-b9f9-4f66-a3f3-c4f94dea955c");
                _http192168178589000admindocsInfo = new RepoItemInfo(this, "Http192168178589000AdminDocs", ".//li[#'admin-menu']/div/a[7]", 30000, null, "540b8f16-5f60-4e64-8db3-19be9482fa1a");
                _databaseInfo = new RepoItemInfo(this, "Database", ".//li[#'admin-menu']//span[@innertext='Database']", 30000, null, "fc93e0d8-86ec-4141-9f19-488ad6ce030a");
                _http192168178589000h2consoleInfo = new RepoItemInfo(this, "Http192168178589000H2Console", ".//li[#'admin-menu']/div/a[8]", 30000, null, "3765b502-c978-4a50-9dd5-820eccfe1358");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9f46552-56c2-4da2-93db-6687b04d3df8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9f46552-56c2-4da2-93db-6687b04d3df8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("ab1d6f40-d693-4489-8a42-aedfe7e5baf7")]
            public virtual Ranorex.SpanTag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("ab1d6f40-d693-4489-8a42-aedfe7e5baf7")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The SignIn1 item.
            /// </summary>
            [RepositoryItem("336f9d5a-0b1a-4da9-bb5b-71167a936423")]
            public virtual Ranorex.SpanTag SignIn1
            {
                get
                {
                    return _signin1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignIn1 item info.
            /// </summary>
            [RepositoryItemInfo("336f9d5a-0b1a-4da9-bb5b-71167a936423")]
            public virtual RepoItemInfo SignIn1Info
            {
                get
                {
                    return _signin1Info;
                }
            }

            /// <summary>
            /// The Http192168178589000Hash item.
            /// </summary>
            [RepositoryItem("4ee167e1-c819-4a66-a6fe-84ff6865f41f")]
            public virtual Ranorex.ATag Http192168178589000Hash
            {
                get
                {
                    return _http192168178589000hashInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000Hash item info.
            /// </summary>
            [RepositoryItemInfo("4ee167e1-c819-4a66-a6fe-84ff6865f41f")]
            public virtual RepoItemInfo Http192168178589000HashInfo
            {
                get
                {
                    return _http192168178589000hashInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d57cdec9-7d51-4047-93ff-62aea8d4ef59")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d57cdec9-7d51-4047-93ff-62aea8d4ef59")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The BtnBtnPrimary item.
            /// </summary>
            [RepositoryItem("f99133cb-fba0-405a-9dc5-e9a58948c1ec")]
            public virtual Ranorex.ButtonTag BtnBtnPrimary
            {
                get
                {
                    return _btnbtnprimaryInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnPrimary item info.
            /// </summary>
            [RepositoryItemInfo("f99133cb-fba0-405a-9dc5-e9a58948c1ec")]
            public virtual RepoItemInfo BtnBtnPrimaryInfo
            {
                get
                {
                    return _btnbtnprimaryInfo;
                }
            }

            /// <summary>
            /// The AlertAlertSuccessFadeShow item.
            /// </summary>
            [RepositoryItem("6ad9825c-3f4e-454f-8ef7-13356c086be4")]
            public virtual Ranorex.DivTag AlertAlertSuccessFadeShow
            {
                get
                {
                    return _alertalertsuccessfadeshowInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AlertAlertSuccessFadeShow item info.
            /// </summary>
            [RepositoryItemInfo("6ad9825c-3f4e-454f-8ef7-13356c086be4")]
            public virtual RepoItemInfo AlertAlertSuccessFadeShowInfo
            {
                get
                {
                    return _alertalertsuccessfadeshowInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("613d6c04-1432-4a11-9b27-491480995bde")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("613d6c04-1432-4a11-9b27-491480995bde")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("8fae3609-9492-48cf-aa07-8917bbd6fd66")]
            public virtual Ranorex.SpanTag Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("8fae3609-9492-48cf-aa07-8917bbd6fd66")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The Register1 item.
            /// </summary>
            [RepositoryItem("a32bd765-028a-45b3-b7ef-b2177d1160b3")]
            public virtual Ranorex.SpanTag Register1
            {
                get
                {
                    return _register1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Register1 item info.
            /// </summary>
            [RepositoryItemInfo("a32bd765-028a-45b3-b7ef-b2177d1160b3")]
            public virtual RepoItemInfo Register1Info
            {
                get
                {
                    return _register1Info;
                }
            }

            /// <summary>
            /// The ToastifyToastBody item.
            /// </summary>
            [RepositoryItem("6078dc83-0369-4741-834f-2aa4d9c85b77")]
            public virtual Ranorex.DivTag ToastifyToastBody
            {
                get
                {
                    return _toastifytoastbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ToastifyToastBody item info.
            /// </summary>
            [RepositoryItemInfo("6078dc83-0369-4741-834f-2aa4d9c85b77")]
            public virtual RepoItemInfo ToastifyToastBodyInfo
            {
                get
                {
                    return _toastifytoastbodyInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("a8feeaa2-da9e-4868-8f26-d31e21c66235")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("a8feeaa2-da9e-4868-8f26-d31e21c66235")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The SecondPassword item.
            /// </summary>
            [RepositoryItem("b22840fd-5069-4b6e-9615-d234454d4fb4")]
            public virtual Ranorex.InputTag SecondPassword
            {
                get
                {
                    return _secondpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SecondPassword item info.
            /// </summary>
            [RepositoryItemInfo("b22840fd-5069-4b6e-9615-d234454d4fb4")]
            public virtual RepoItemInfo SecondPasswordInfo
            {
                get
                {
                    return _secondpasswordInfo;
                }
            }

            /// <summary>
            /// The SpanTagPleaseCheckYourEmailForConf item.
            /// </summary>
            [RepositoryItem("74055951-5198-43ad-8ce3-9f74d4df8a3d")]
            public virtual Ranorex.SpanTag SpanTagPleaseCheckYourEmailForConf
            {
                get
                {
                    return _spantagpleasecheckyouremailforconfInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagPleaseCheckYourEmailForConf item info.
            /// </summary>
            [RepositoryItemInfo("74055951-5198-43ad-8ce3-9f74d4df8a3d")]
            public virtual RepoItemInfo SpanTagPleaseCheckYourEmailForConfInfo
            {
                get
                {
                    return _spantagpleasecheckyouremailforconfInfo;
                }
            }

            /// <summary>
            /// The Account item.
            /// </summary>
            [RepositoryItem("ae449e60-cbd1-418e-a9ee-7c10ecb6af00")]
            public virtual Ranorex.SpanTag Account
            {
                get
                {
                    return _accountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account item info.
            /// </summary>
            [RepositoryItemInfo("ae449e60-cbd1-418e-a9ee-7c10ecb6af00")]
            public virtual RepoItemInfo AccountInfo
            {
                get
                {
                    return _accountInfo;
                }
            }

            /// <summary>
            /// The FirstPassword item.
            /// </summary>
            [RepositoryItem("7fc91c0d-8ad2-4525-a2cc-3bf09fc3bc51")]
            public virtual Ranorex.InputTag FirstPassword
            {
                get
                {
                    return _firstpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstPassword item info.
            /// </summary>
            [RepositoryItemInfo("7fc91c0d-8ad2-4525-a2cc-3bf09fc3bc51")]
            public virtual RepoItemInfo FirstPasswordInfo
            {
                get
                {
                    return _firstpasswordInfo;
                }
            }

            /// <summary>
            /// The RegisterSubmit item.
            /// </summary>
            [RepositoryItem("ebb00c23-7048-4248-9374-dec251df4184")]
            public virtual Ranorex.ButtonTag RegisterSubmit
            {
                get
                {
                    return _registersubmitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RegisterSubmit item info.
            /// </summary>
            [RepositoryItemInfo("ebb00c23-7048-4248-9374-dec251df4184")]
            public virtual RepoItemInfo RegisterSubmitInfo
            {
                get
                {
                    return _registersubmitInfo;
                }
            }

            /// <summary>
            /// The LoginItem item.
            /// </summary>
            [RepositoryItem("49d571a7-49c3-4eff-84d8-d9d6541532a3")]
            public virtual Ranorex.ATag LoginItem
            {
                get
                {
                    return _loginitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LoginItem item info.
            /// </summary>
            [RepositoryItemInfo("49d571a7-49c3-4eff-84d8-d9d6541532a3")]
            public virtual RepoItemInfo LoginItemInfo
            {
                get
                {
                    return _loginitemInfo;
                }
            }

            /// <summary>
            /// The Settings item.
            /// </summary>
            [RepositoryItem("71ce774c-53af-4e69-b139-e36356930e7f")]
            public virtual Ranorex.SpanTag Settings
            {
                get
                {
                    return _settingsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Settings item info.
            /// </summary>
            [RepositoryItemInfo("71ce774c-53af-4e69-b139-e36356930e7f")]
            public virtual RepoItemInfo SettingsInfo
            {
                get
                {
                    return _settingsInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f111b160-075a-4335-a363-68770df90664")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f111b160-075a-4335-a363-68770df90664")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The BtnBtnPrimary1 item.
            /// </summary>
            [RepositoryItem("26906082-4f7a-4cf2-974d-9a19dc228da5")]
            public virtual Ranorex.ButtonTag BtnBtnPrimary1
            {
                get
                {
                    return _btnbtnprimary1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnPrimary1 item info.
            /// </summary>
            [RepositoryItemInfo("26906082-4f7a-4cf2-974d-9a19dc228da5")]
            public virtual RepoItemInfo BtnBtnPrimary1Info
            {
                get
                {
                    return _btnbtnprimary1Info;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("50943198-4f91-4256-8031-6311c4574f56")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("50943198-4f91-4256-8031-6311c4574f56")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Http192168178589000AccountSetti item.
            /// </summary>
            [RepositoryItem("f103ffc2-9035-4717-8f8d-5f5eabe93368")]
            public virtual Ranorex.ATag Http192168178589000AccountSetti
            {
                get
                {
                    return _http192168178589000accountsettiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000AccountSetti item info.
            /// </summary>
            [RepositoryItemInfo("f103ffc2-9035-4717-8f8d-5f5eabe93368")]
            public virtual RepoItemInfo Http192168178589000AccountSettiInfo
            {
                get
                {
                    return _http192168178589000accountsettiInfo;
                }
            }

            /// <summary>
            /// The Http192168178589000AccountPassw item.
            /// </summary>
            [RepositoryItem("637afc29-f373-40a2-9466-77ec3c3de201")]
            public virtual Ranorex.ATag Http192168178589000AccountPassw
            {
                get
                {
                    return _http192168178589000accountpasswInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000AccountPassw item info.
            /// </summary>
            [RepositoryItemInfo("637afc29-f373-40a2-9466-77ec3c3de201")]
            public virtual RepoItemInfo Http192168178589000AccountPasswInfo
            {
                get
                {
                    return _http192168178589000accountpasswInfo;
                }
            }

            /// <summary>
            /// The CurrentPassword item.
            /// </summary>
            [RepositoryItem("4113adcd-5d2f-4db8-970f-2025a7376a4f")]
            public virtual Ranorex.InputTag CurrentPassword
            {
                get
                {
                    return _currentpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CurrentPassword item info.
            /// </summary>
            [RepositoryItemInfo("4113adcd-5d2f-4db8-970f-2025a7376a4f")]
            public virtual RepoItemInfo CurrentPasswordInfo
            {
                get
                {
                    return _currentpasswordInfo;
                }
            }

            /// <summary>
            /// The NewPassword item.
            /// </summary>
            [RepositoryItem("15c7dfe2-a3ff-456b-9dbb-137fedc64722")]
            public virtual Ranorex.InputTag NewPassword
            {
                get
                {
                    return _newpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewPassword item info.
            /// </summary>
            [RepositoryItemInfo("15c7dfe2-a3ff-456b-9dbb-137fedc64722")]
            public virtual RepoItemInfo NewPasswordInfo
            {
                get
                {
                    return _newpasswordInfo;
                }
            }

            /// <summary>
            /// The ConfirmPassword item.
            /// </summary>
            [RepositoryItem("206baca1-e2ea-4dac-b2e0-41d8b4f50ceb")]
            public virtual Ranorex.InputTag ConfirmPassword
            {
                get
                {
                    return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("206baca1-e2ea-4dac-b2e0-41d8b4f50ceb")]
            public virtual RepoItemInfo ConfirmPasswordInfo
            {
                get
                {
                    return _confirmpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnBtnSuccess item.
            /// </summary>
            [RepositoryItem("e9f2db67-1cbe-4198-a35e-4821a01ddc44")]
            public virtual Ranorex.ButtonTag BtnBtnSuccess
            {
                get
                {
                    return _btnbtnsuccessInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnSuccess item info.
            /// </summary>
            [RepositoryItemInfo("e9f2db67-1cbe-4198-a35e-4821a01ddc44")]
            public virtual RepoItemInfo BtnBtnSuccessInfo
            {
                get
                {
                    return _btnbtnsuccessInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("61fe6c89-abc9-47d9-9441-bf30c1b683ab")]
            public virtual Ranorex.SpanTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("61fe6c89-abc9-47d9-9441-bf30c1b683ab")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("3e575f67-e73d-49ee-8b86-fc22c318d9cf")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("3e575f67-e73d-49ee-8b86-fc22c318d9cf")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }

            /// <summary>
            /// The Password1 item.
            /// </summary>
            [RepositoryItem("4e66dd21-fe6e-4145-8907-a96ceeea9605")]
            public virtual Ranorex.SpanTag Password1
            {
                get
                {
                    return _password1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Password1 item info.
            /// </summary>
            [RepositoryItemInfo("4e66dd21-fe6e-4145-8907-a96ceeea9605")]
            public virtual RepoItemInfo Password1Info
            {
                get
                {
                    return _password1Info;
                }
            }

            /// <summary>
            /// The Http192168178589000Hash1 item.
            /// </summary>
            [RepositoryItem("286e6589-9b22-4724-801e-920de9a22171")]
            public virtual Ranorex.ATag Http192168178589000Hash1
            {
                get
                {
                    return _http192168178589000hash1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000Hash1 item info.
            /// </summary>
            [RepositoryItemInfo("286e6589-9b22-4724-801e-920de9a22171")]
            public virtual RepoItemInfo Http192168178589000Hash1Info
            {
                get
                {
                    return _http192168178589000hash1Info;
                }
            }

            /// <summary>
            /// The Http192168178589000AdminUserMa item.
            /// </summary>
            [RepositoryItem("948fe97d-ddec-4a93-a48f-7531e85c483e")]
            public virtual Ranorex.ATag Http192168178589000AdminUserMa
            {
                get
                {
                    return _http192168178589000adminusermaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000AdminUserMa item info.
            /// </summary>
            [RepositoryItemInfo("948fe97d-ddec-4a93-a48f-7531e85c483e")]
            public virtual RepoItemInfo Http192168178589000AdminUserMaInfo
            {
                get
                {
                    return _http192168178589000adminusermaInfo;
                }
            }

            /// <summary>
            /// The CreateANewUser item.
            /// </summary>
            [RepositoryItem("2d0d78c2-555f-4edb-b54c-6c79ab348d15")]
            public virtual Ranorex.SpanTag CreateANewUser
            {
                get
                {
                    return _createanewuserInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreateANewUser item info.
            /// </summary>
            [RepositoryItemInfo("2d0d78c2-555f-4edb-b54c-6c79ab348d15")]
            public virtual RepoItemInfo CreateANewUserInfo
            {
                get
                {
                    return _createanewuserInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("d4a6f2b2-3884-49f6-ab52-41246b1c5af7")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("d4a6f2b2-3884-49f6-ab52-41246b1c5af7")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The ROLEUSER item.
            /// </summary>
            [RepositoryItem("f3e92086-04de-44dd-b488-aa9dbfaa6115")]
            public virtual Ranorex.OptionTag ROLEUSER
            {
                get
                {
                    return _roleuserInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The ROLEUSER item info.
            /// </summary>
            [RepositoryItemInfo("f3e92086-04de-44dd-b488-aa9dbfaa6115")]
            public virtual RepoItemInfo ROLEUSERInfo
            {
                get
                {
                    return _roleuserInfo;
                }
            }

            /// <summary>
            /// The Save1 item.
            /// </summary>
            [RepositoryItem("d12c1bcf-5be1-4fc9-a800-d735f2de612d")]
            public virtual Ranorex.SpanTag Save1
            {
                get
                {
                    return _save1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save1 item info.
            /// </summary>
            [RepositoryItemInfo("d12c1bcf-5be1-4fc9-a800-d735f2de612d")]
            public virtual RepoItemInfo Save1Info
            {
                get
                {
                    return _save1Info;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("f0eb9458-b2d0-4280-8ed8-b646b0c9f8ec")]
            public virtual Ranorex.SpanTag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("f0eb9458-b2d0-4280-8ed8-b646b0c9f8ec")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Delete1 item.
            /// </summary>
            [RepositoryItem("520c85ef-8372-46d0-95f8-ace692dc6fc6")]
            public virtual Ranorex.SpanTag Delete1
            {
                get
                {
                    return _delete1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Delete1 item info.
            /// </summary>
            [RepositoryItemInfo("520c85ef-8372-46d0-95f8-ace692dc6fc6")]
            public virtual RepoItemInfo Delete1Info
            {
                get
                {
                    return _delete1Info;
                }
            }

            /// <summary>
            /// The Administration item.
            /// </summary>
            [RepositoryItem("e74f0e29-8c91-4909-86fb-f2efffd2a029")]
            public virtual Ranorex.SpanTag Administration
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Administration item info.
            /// </summary>
            [RepositoryItemInfo("e74f0e29-8c91-4909-86fb-f2efffd2a029")]
            public virtual RepoItemInfo AdministrationInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The UserManagement item.
            /// </summary>
            [RepositoryItem("fe80d8ce-bb0a-4913-a8c4-775a60019f84")]
            public virtual Ranorex.SpanTag UserManagement
            {
                get
                {
                    return _usermanagementInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UserManagement item info.
            /// </summary>
            [RepositoryItemInfo("fe80d8ce-bb0a-4913-a8c4-775a60019f84")]
            public virtual RepoItemInfo UserManagementInfo
            {
                get
                {
                    return _usermanagementInfo;
                }
            }

            /// <summary>
            /// The View item.
            /// </summary>
            [RepositoryItem("e96853f8-6335-4b31-a31f-a2dbbcafa060")]
            public virtual Ranorex.SpanTag View
            {
                get
                {
                    return _viewInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The View item info.
            /// </summary>
            [RepositoryItemInfo("e96853f8-6335-4b31-a31f-a2dbbcafa060")]
            public virtual RepoItemInfo ViewInfo
            {
                get
                {
                    return _viewInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("790f08a8-387c-4254-a1b8-3e3307a28ae8")]
            public virtual Ranorex.SpanTag Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("790f08a8-387c-4254-a1b8-3e3307a28ae8")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("edc0f65c-b78d-4e3a-b9c5-f7a8b46eee94")]
            public virtual Ranorex.SpanTag Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("edc0f65c-b78d-4e3a-b9c5-f7a8b46eee94")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The BtnBtnPrimary2 item.
            /// </summary>
            [RepositoryItem("270ba79e-b9f9-4f66-a3f3-c4f94dea955c")]
            public virtual Ranorex.ButtonTag BtnBtnPrimary2
            {
                get
                {
                    return _btnbtnprimary2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnPrimary2 item info.
            /// </summary>
            [RepositoryItemInfo("270ba79e-b9f9-4f66-a3f3-c4f94dea955c")]
            public virtual RepoItemInfo BtnBtnPrimary2Info
            {
                get
                {
                    return _btnbtnprimary2Info;
                }
            }

            /// <summary>
            /// The Http192168178589000AdminDocs item.
            /// </summary>
            [RepositoryItem("540b8f16-5f60-4e64-8db3-19be9482fa1a")]
            public virtual Ranorex.ATag Http192168178589000AdminDocs
            {
                get
                {
                    return _http192168178589000admindocsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000AdminDocs item info.
            /// </summary>
            [RepositoryItemInfo("540b8f16-5f60-4e64-8db3-19be9482fa1a")]
            public virtual RepoItemInfo Http192168178589000AdminDocsInfo
            {
                get
                {
                    return _http192168178589000admindocsInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("fc93e0d8-86ec-4141-9f19-488ad6ce030a")]
            public virtual Ranorex.SpanTag Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("fc93e0d8-86ec-4141-9f19-488ad6ce030a")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The Http192168178589000H2Console item.
            /// </summary>
            [RepositoryItem("3765b502-c978-4a50-9dd5-820eccfe1358")]
            public virtual Ranorex.ATag Http192168178589000H2Console
            {
                get
                {
                    return _http192168178589000h2consoleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Http192168178589000H2Console item info.
            /// </summary>
            [RepositoryItemInfo("3765b502-c978-4a50-9dd5-820eccfe1358")]
            public virtual RepoItemInfo Http192168178589000H2ConsoleInfo
            {
                get
                {
                    return _http192168178589000h2consoleInfo;
                }
            }

            /// <summary>
            /// The OperationsAccountResourceIsAuthentica folder.
            /// </summary>
            [RepositoryFolder("c05c03c8-4ab4-42d5-bef1-e73cddfb78a4")]
            public virtual PerformanceRatingRepositoryFolders.OperationsAccountResourceIsAuthenticaFolder OperationsAccountResourceIsAuthentica
            {
                get { return _operationsaccountresourceisauthentica; }
            }
        }

        /// <summary>
        /// The OperationsAccountResourceIsAuthenticaFolder folder.
        /// </summary>
        [RepositoryFolder("c05c03c8-4ab4-42d5-bef1-e73cddfb78a4")]
        public partial class OperationsAccountResourceIsAuthenticaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _isauthenticatedInfo;
            RepoItemInfo _tryitoutInfo;
            RepoItemInfo _executeInfo;

            /// <summary>
            /// Creates a new OperationsAccountResourceIsAuthentica  folder.
            /// </summary>
            public OperationsAccountResourceIsAuthenticaFolder(RepoGenBaseFolder parentFolder) :
                    base("OperationsAccountResourceIsAuthentica", ".//div[#'app-view-container']/div[1]//iframe[@src='http://192.168.178.58:9000/swagger-ui/index.html']//div[#'operations-account-resource-isAuthenticatedUsingGET']", parentFolder, 30000, null, false, "c05c03c8-4ab4-42d5-bef1-e73cddfb78a4", "")
            {
                _isauthenticatedInfo = new RepoItemInfo(this, "IsAuthenticated", "?/?/div[@innertext='isAuthenticated']", 30000, null, "44965bc6-a519-4318-a00e-a51ea11e75e8");
                _tryitoutInfo = new RepoItemInfo(this, "TryItOut", "div[2]/div/div[1]//button[@innertext='Try it out ']", 30000, null, "209e03e5-a327-41da-812d-2c95ef551662");
                _executeInfo = new RepoItemInfo(this, "Execute", "div[2]/div/div[2]/button[@innertext='Execute']", 30000, null, "4969386a-6f1e-411e-9985-5939756b03ca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c05c03c8-4ab4-42d5-bef1-e73cddfb78a4")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c05c03c8-4ab4-42d5-bef1-e73cddfb78a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IsAuthenticated item.
            /// </summary>
            [RepositoryItem("44965bc6-a519-4318-a00e-a51ea11e75e8")]
            public virtual Ranorex.DivTag IsAuthenticated
            {
                get
                {
                    return _isauthenticatedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The IsAuthenticated item info.
            /// </summary>
            [RepositoryItemInfo("44965bc6-a519-4318-a00e-a51ea11e75e8")]
            public virtual RepoItemInfo IsAuthenticatedInfo
            {
                get
                {
                    return _isauthenticatedInfo;
                }
            }

            /// <summary>
            /// The TryItOut item.
            /// </summary>
            [RepositoryItem("209e03e5-a327-41da-812d-2c95ef551662")]
            public virtual Ranorex.ButtonTag TryItOut
            {
                get
                {
                    return _tryitoutInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TryItOut item info.
            /// </summary>
            [RepositoryItemInfo("209e03e5-a327-41da-812d-2c95ef551662")]
            public virtual RepoItemInfo TryItOutInfo
            {
                get
                {
                    return _tryitoutInfo;
                }
            }

            /// <summary>
            /// The Execute item.
            /// </summary>
            [RepositoryItem("4969386a-6f1e-411e-9985-5939756b03ca")]
            public virtual Ranorex.ButtonTag Execute
            {
                get
                {
                    return _executeInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Execute item info.
            /// </summary>
            [RepositoryItemInfo("4969386a-6f1e-411e-9985-5939756b03ca")]
            public virtual RepoItemInfo ExecuteInfo
            {
                get
                {
                    return _executeInfo;
                }
            }
        }

        /// <summary>
        /// The PerformanceRatingGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("0ae15e82-60b5-4fac-9011-219a41e3dbd3")]
        public partial class PerformanceRatingGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _neuladenInfo;
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new PerformanceRatingGoogleChrome  folder.
            /// </summary>
            public PerformanceRatingGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PerformanceRatingGoogleChrome", "/form[@title>'PerformanceRating - Google']", parentFolder, 30000, null, true, "0ae15e82-60b5-4fac-9011-219a41e3dbd3", "")
            {
                _neuladenInfo = new RepoItemInfo(this, "NeuLaden", "container[@accessiblename>'PerformanceRating - Google']/container[@accessiblename='Google Chrome']//button[@accessiblename='Neu laden']", 30000, null, "a2cddc96-1376-43f3-b691-920b6e3b8c60");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'PerformanceRating - Google']/container/container[2]/container[1]", 30000, null, "a8c480b2-715d-4ef4-817b-9ba6fdf4a3c9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ae15e82-60b5-4fac-9011-219a41e3dbd3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ae15e82-60b5-4fac-9011-219a41e3dbd3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NeuLaden item.
            /// </summary>
            [RepositoryItem("a2cddc96-1376-43f3-b691-920b6e3b8c60")]
            public virtual Ranorex.Button NeuLaden
            {
                get
                {
                    return _neuladenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NeuLaden item info.
            /// </summary>
            [RepositoryItemInfo("a2cddc96-1376-43f3-b691-920b6e3b8c60")]
            public virtual RepoItemInfo NeuLadenInfo
            {
                get
                {
                    return _neuladenInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("a8c480b2-715d-4ef4-817b-9ba6fdf4a3c9")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("a8c480b2-715d-4ef4-817b-9ba6fdf4a3c9")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("864e7185-a511-45ab-a104-5a7dcb3b633d")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexstudio1aktivesfensterInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "864e7185-a511-45ab-a104-5a7dcb3b633d", "")
            {
                _ranorexstudio1aktivesfensterInfo = new RepoItemInfo(this, "RanorexStudio1AktivesFenster", "container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[7]", 30000, null, "9c6d8e80-a50a-4418-bc62-0c00b247dd8e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("864e7185-a511-45ab-a104-5a7dcb3b633d")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("864e7185-a511-45ab-a104-5a7dcb3b633d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio1AktivesFenster item.
            /// </summary>
            [RepositoryItem("9c6d8e80-a50a-4418-bc62-0c00b247dd8e")]
            public virtual Ranorex.Button RanorexStudio1AktivesFenster
            {
                get
                {
                    return _ranorexstudio1aktivesfensterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio1AktivesFenster item info.
            /// </summary>
            [RepositoryItemInfo("9c6d8e80-a50a-4418-bc62-0c00b247dd8e")]
            public virtual RepoItemInfo RanorexStudio1AktivesFensterInfo
            {
                get
                {
                    return _ranorexstudio1aktivesfensterInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
