///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording3 recording.
    /// </summary>
    [TestModule("1edb35d9-f684-4889-b7f1-34167df810c9", ModuleType.Recording, 1)]
    public partial class Recording3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerformanceRatingRepository repository.
        /// </summary>
        public static PerformanceRatingRepository repo = PerformanceRatingRepository.Instance;

        static Recording3 instance = new Recording3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.AdressUndSuchleiste' at 94;10.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(0));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.Click("94;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.AdressUndSuchleiste' at 92;13.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(1));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.Click("92;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GoogleGoogleChrome.AdressUndSuchleiste' at 164;14.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(2));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.MoveTo("164;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GoogleGoogleChrome.AdressUndSuchleiste' at 5;24.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(3));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.MoveTo("5;24");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'h' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(4));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press("h");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ttp{RShiftKey down}:{RShiftKey up}{RShiftKey down}//{RShiftKey up}192.' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(5));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press("ttp{RShiftKey down}:{RShiftKey up}{RShiftKey down}//{RShiftKey up}192.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '168' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(6));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press("168");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.178' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(7));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press(".178");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.58{RShiftKey down}:{RShiftKey up}9000{Return}' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(8));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press(".58{RShiftKey down}:{RShiftKey up}9000{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating' at 1880;31.", repo.PerformanceRating.SelfInfo, new RecordItemIndex(9));
            repo.PerformanceRating.Self.Click("1880;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Register' at 36;12.", repo.PerformanceRating.RegisterInfo, new RecordItemIndex(10));
            repo.PerformanceRating.Register.Click("36;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Username' at 269;22.", repo.PerformanceRating.UsernameInfo, new RecordItemIndex(11));
            repo.PerformanceRating.Username.Click("269;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user' with focus on 'PerformanceRating.Username'.", repo.PerformanceRating.UsernameInfo, new RecordItemIndex(12));
            repo.PerformanceRating.Username.PressKeys("user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Email' at 295;20.", repo.PerformanceRating.EmailInfo, new RecordItemIndex(13));
            repo.PerformanceRating.Email.Click("295;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}mail.com' with focus on 'PerformanceRating.Email'.", repo.PerformanceRating.EmailInfo, new RecordItemIndex(14));
            repo.PerformanceRating.Email.PressKeys("user{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}mail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.FirstPassword' at 202;11.", repo.PerformanceRating.FirstPasswordInfo, new RecordItemIndex(15));
            repo.PerformanceRating.FirstPassword.Click("202;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user' with focus on 'PerformanceRating.FirstPassword'.", repo.PerformanceRating.FirstPasswordInfo, new RecordItemIndex(16));
            repo.PerformanceRating.FirstPassword.PressKeys("user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.SecondPassword' at 179;19.", repo.PerformanceRating.SecondPasswordInfo, new RecordItemIndex(17));
            repo.PerformanceRating.SecondPassword.Click("179;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user' with focus on 'PerformanceRating.SecondPassword'.", repo.PerformanceRating.SecondPasswordInfo, new RecordItemIndex(18));
            repo.PerformanceRating.SecondPassword.PressKeys("user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.RegisterSubmit' at 27;7.", repo.PerformanceRating.RegisterSubmitInfo, new RecordItemIndex(19));
            repo.PerformanceRating.RegisterSubmit.Click("27;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
