///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording11 recording.
    /// </summary>
    [TestModule("453fbe50-1ba2-48a7-b252-19a3ef58c297", ModuleType.Recording, 1)]
    public partial class Recording11 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerformanceRatingRepository repository.
        /// </summary>
        public static PerformanceRatingRepository repo = PerformanceRatingRepository.Instance;

        static Recording11 instance = new Recording11();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording11()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording11 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.Pane1' at 270;18.", repo.GoogleGoogleChrome.Pane1Info, new RecordItemIndex(0));
            repo.GoogleGoogleChrome.Pane1.Click("270;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'h{Return}' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(1));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press("h{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Account' at 53;18.", repo.PerformanceRating.AccountInfo, new RecordItemIndex(2));
            repo.PerformanceRating.Account.Click("53;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LoginItem' at 127;8.", repo.PerformanceRating.LoginItemInfo, new RecordItemIndex(3));
            repo.PerformanceRating.LoginItem.Click("127;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'PerformanceRating.Username'.", repo.PerformanceRating.UsernameInfo, new RecordItemIndex(4));
            repo.PerformanceRating.Username.EnsureVisible();
            Keyboard.Press("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Password' at 261;22.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(5));
            repo.PerformanceRating.Password.Click("261;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'PerformanceRating.Password'.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(6));
            repo.PerformanceRating.Password.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.SignIn1' at 30;-1.", repo.PerformanceRating.SignIn1Info, new RecordItemIndex(7));
            repo.PerformanceRating.SignIn1.Click("30;-1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Http192168178589000Hash1' at 140;9.", repo.PerformanceRating.Http192168178589000Hash1Info, new RecordItemIndex(8));
            repo.PerformanceRating.Http192168178589000Hash1.Click("140;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Http192168178589000AdminUserMa' at 183;12.", repo.PerformanceRating.Http192168178589000AdminUserMaInfo, new RecordItemIndex(9));
            repo.PerformanceRating.Http192168178589000AdminUserMa.Click("183;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.CreateANewUser' at 22;18.", repo.PerformanceRating.CreateANewUserInfo, new RecordItemIndex(10));
            repo.PerformanceRating.CreateANewUser.Click("22;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Login' at 655;21.", repo.PerformanceRating.LoginInfo, new RecordItemIndex(11));
            repo.PerformanceRating.Login.Click("655;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'usertest' with focus on 'PerformanceRating.Login'.", repo.PerformanceRating.LoginInfo, new RecordItemIndex(12));
            repo.PerformanceRating.Login.PressKeys("usertest");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 90 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(90);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.FirstName' at 584;15.", repo.PerformanceRating.FirstNameInfo, new RecordItemIndex(14));
            repo.PerformanceRating.FirstName.Click("584;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'usertest' with focus on 'PerformanceRating.FirstName'.", repo.PerformanceRating.FirstNameInfo, new RecordItemIndex(15));
            repo.PerformanceRating.FirstName.PressKeys("usertest");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LastName' at 542;17.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(16));
            repo.PerformanceRating.LastName.Click("542;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'usertest' with focus on 'PerformanceRating.LastName'.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(17));
            repo.PerformanceRating.LastName.PressKeys("usertest");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Email' at 500;19.", repo.PerformanceRating.EmailInfo, new RecordItemIndex(18));
            repo.PerformanceRating.Email.Click("500;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'usertest{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}mail.com' with focus on 'PerformanceRating.Email'.", repo.PerformanceRating.EmailInfo, new RecordItemIndex(19));
            repo.PerformanceRating.Email.PressKeys("usertest{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}mail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.ROLEUSER' at 107;4.", repo.PerformanceRating.ROLEUSERInfo, new RecordItemIndex(20));
            repo.PerformanceRating.ROLEUSER.Click("107;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Save1' at 9;8.", repo.PerformanceRating.Save1Info, new RecordItemIndex(21));
            repo.PerformanceRating.Save1.Click("9;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Delete' at 12;7.", repo.PerformanceRating.DeleteInfo, new RecordItemIndex(22));
            repo.PerformanceRating.Delete.Click("12;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Delete1' at 34;5.", repo.PerformanceRating.Delete1Info, new RecordItemIndex(23));
            repo.PerformanceRating.Delete1.Click("34;5");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
