///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording14 recording.
    /// </summary>
    [TestModule("b60e3b26-872c-40da-969e-ae7184d70e6b", ModuleType.Recording, 1)]
    public partial class Recording14 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerformanceRatingRepository repository.
        /// </summary>
        public static PerformanceRatingRepository repo = PerformanceRatingRepository.Instance;

        static Recording14 instance = new Recording14();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording14()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording14 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Google.DivTagGb' at 148;-16.", repo.Google.DivTagGbInfo, new RecordItemIndex(0));
            repo.Google.DivTagGb.Click("148;-16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'http://192.168.178.58:9000/' with focus on 'Google'.", repo.Google.SelfInfo, new RecordItemIndex(1));
            repo.Google.Self.EnsureVisible();
            Keyboard.Press("http://192.168.178.58:9000/");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}'.", new RecordItemIndex(2));
            Keyboard.Press("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Account' at 33;2.", repo.PerformanceRating.AccountInfo, new RecordItemIndex(3));
            repo.PerformanceRating.Account.Click("33;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LoginItem' at 106;8.", repo.PerformanceRating.LoginItemInfo, new RecordItemIndex(4));
            repo.PerformanceRating.LoginItem.Click("106;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'PerformanceRating.Username'.", repo.PerformanceRating.UsernameInfo, new RecordItemIndex(5));
            repo.PerformanceRating.Username.EnsureVisible();
            Keyboard.Press("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Password' at 362;21.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(6));
            repo.PerformanceRating.Password.Click("362;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'PerformanceRating.Password'.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(7));
            repo.PerformanceRating.Password.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.SignIn1' at 24;13.", repo.PerformanceRating.SignIn1Info, new RecordItemIndex(8));
            repo.PerformanceRating.SignIn1.Click("24;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Administration' at 27;12.", repo.PerformanceRating.AdministrationInfo, new RecordItemIndex(9));
            repo.PerformanceRating.Administration.Click("27;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Http192168178589000AdminDocs' at 89;3.", repo.PerformanceRating.Http192168178589000AdminDocsInfo, new RecordItemIndex(10));
            repo.PerformanceRating.Http192168178589000AdminDocs.Click("89;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -870 units.", new RecordItemIndex(11));
            Mouse.ScrollWheel(-870);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.OperationsAccountResourceIsAuthentica.IsAuthenticated' at 285;2.", repo.PerformanceRating.OperationsAccountResourceIsAuthentica.IsAuthenticatedInfo, new RecordItemIndex(12));
            repo.PerformanceRating.OperationsAccountResourceIsAuthentica.IsAuthenticated.Click("285;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.OperationsAccountResourceIsAuthentica.TryItOut' at 57;5.", repo.PerformanceRating.OperationsAccountResourceIsAuthentica.TryItOutInfo, new RecordItemIndex(13));
            repo.PerformanceRating.OperationsAccountResourceIsAuthentica.TryItOut.Click("57;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.OperationsAccountResourceIsAuthentica.Execute' at 700;14.", repo.PerformanceRating.OperationsAccountResourceIsAuthentica.ExecuteInfo, new RecordItemIndex(14));
            repo.PerformanceRating.OperationsAccountResourceIsAuthentica.Execute.Click("700;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRatingGoogleChrome.Pane' at 902;6.", repo.PerformanceRatingGoogleChrome.PaneInfo, new RecordItemIndex(15));
            repo.PerformanceRatingGoogleChrome.Pane.Click("902;6");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
