///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording7 recording.
    /// </summary>
    [TestModule("b1be0b4d-3512-429a-803e-2a8a2dff07f3", ModuleType.Recording, 1)]
    public partial class Recording7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerformanceRatingRepository repository.
        /// </summary>
        public static PerformanceRatingRepository repo = PerformanceRatingRepository.Instance;

        static Recording7 instance = new Recording7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.AdressUndSuchleiste' at 174;20.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(0));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.Click("174;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'h{Return}' with focus on 'GoogleGoogleChrome.AdressUndSuchleiste'.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(1));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.PressKeys("h{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Http192168178589000Hash' at 91;16.", repo.PerformanceRating.Http192168178589000HashInfo, new RecordItemIndex(2));
            repo.PerformanceRating.Http192168178589000Hash.Click("91;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LoginItem' at 106;15.", repo.PerformanceRating.LoginItemInfo, new RecordItemIndex(3));
            repo.PerformanceRating.LoginItem.Click("106;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user{Tab}' with focus on 'PerformanceRating'.", repo.PerformanceRating.SelfInfo, new RecordItemIndex(4));
            repo.PerformanceRating.Self.EnsureVisible();
            Keyboard.Press("user{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Password' at 412;18.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(5));
            repo.PerformanceRating.Password.Click("412;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user' with focus on 'PerformanceRating.Password'.", repo.PerformanceRating.PasswordInfo, new RecordItemIndex(6));
            repo.PerformanceRating.Password.PressKeys("user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.BtnBtnPrimary' at 61;6.", repo.PerformanceRating.BtnBtnPrimaryInfo, new RecordItemIndex(7));
            repo.PerformanceRating.BtnBtnPrimary.Click("61;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Http192168178589000Hash' at 93;13.", repo.PerformanceRating.Http192168178589000HashInfo, new RecordItemIndex(8));
            repo.PerformanceRating.Http192168178589000Hash.Click("93;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.Settings' at 37;3.", repo.PerformanceRating.SettingsInfo, new RecordItemIndex(9));
            repo.PerformanceRating.Settings.Click("37;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LastName' at 79;20.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(10));
            repo.PerformanceRating.LastName.Click("79;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '4' with focus on 'PerformanceRating.LastName'.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(11));
            repo.PerformanceRating.LastName.PressKeys("4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.BtnBtnPrimary1' at 17;7.", repo.PerformanceRating.BtnBtnPrimary1Info, new RecordItemIndex(12));
            repo.PerformanceRating.BtnBtnPrimary1.Click("17;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRatingGoogleChrome.NeuLaden' at 14;13.", repo.PerformanceRatingGoogleChrome.NeuLadenInfo, new RecordItemIndex(13));
            repo.PerformanceRatingGoogleChrome.NeuLaden.Click("14;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.LastName' at 92;17.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(14));
            repo.PerformanceRating.LastName.Click("92;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PerformanceRating.LastName'.", repo.PerformanceRating.LastNameInfo, new RecordItemIndex(15));
            repo.PerformanceRating.LastName.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.FirstName' at 87;18.", repo.PerformanceRating.FirstNameInfo, new RecordItemIndex(16));
            repo.PerformanceRating.FirstName.Click("87;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'PerformanceRating.FirstName'.", repo.PerformanceRating.FirstNameInfo, new RecordItemIndex(17));
            repo.PerformanceRating.FirstName.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.BtnBtnPrimary1' at 44;4.", repo.PerformanceRating.BtnBtnPrimary1Info, new RecordItemIndex(18));
            repo.PerformanceRating.BtnBtnPrimary1.Click("44;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
