///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PerformanceRating
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The signInSuccess recording.
    /// </summary>
    [TestModule("e0408175-0015-45fc-a634-7b8deda4c5b1", ModuleType.Recording, 1)]
    public partial class signInSuccess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerformanceRatingRepository repository.
        /// </summary>
        public static PerformanceRatingRepository repo = PerformanceRatingRepository.Instance;

        static signInSuccess instance = new signInSuccess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public signInSuccess()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static signInSuccess Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'www.google.com' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("www.google.com", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoogleGoogleChrome.AdressUndSuchleiste' at 184;10.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(1));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.Click("184;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Google.N1xJcfNe6nSdO3j99' at 323;-21.", repo.Google.N1xJcfNe6nSdO3j99Info, new RecordItemIndex(2));
            repo.Google.N1xJcfNe6nSdO3j99.DoubleClick("323;-21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Google.N1xJcfNe6nSdO3j99' at 323;-21.", repo.Google.N1xJcfNe6nSdO3j99Info, new RecordItemIndex(3));
            repo.Google.N1xJcfNe6nSdO3j99.Click("323;-21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}v{LControlKey up}' with focus on 'GoogleGoogleChrome.AdressUndSuchleiste'.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(4));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.PressKeys("{LControlKey down}v{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GoogleGoogleChrome.Pane' at 194;20.", repo.GoogleGoogleChrome.PaneInfo, new RecordItemIndex(5));
            repo.GoogleGoogleChrome.Pane.MoveTo("194;20");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GoogleGoogleChrome.Pane' at 23;13.", repo.GoogleGoogleChrome.PaneInfo, new RecordItemIndex(6));
            repo.GoogleGoogleChrome.Pane.MoveTo("23;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Return}' with focus on 'GoogleGoogleChrome.AdressUndSuchleiste'.", repo.GoogleGoogleChrome.AdressUndSuchleisteInfo, new RecordItemIndex(7));
            repo.GoogleGoogleChrome.AdressUndSuchleiste.PressKeys("{Back}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating' at 1878;26.", repo.PerformanceRating.SelfInfo, new RecordItemIndex(8));
            repo.PerformanceRating.Self.Click("1878;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.SignIn' at 33;7.", repo.PerformanceRating.SignInInfo, new RecordItemIndex(9));
            repo.PerformanceRating.SignIn.Click("33;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user{Tab}user' with focus on 'PerformanceRating'.", repo.PerformanceRating.SelfInfo, new RecordItemIndex(10));
            repo.PerformanceRating.Self.EnsureVisible();
            Keyboard.Press("user{Tab}user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerformanceRating.SignIn1' at 43;8.", repo.PerformanceRating.SignIn1Info, new RecordItemIndex(11));
            repo.PerformanceRating.SignIn1.Click("43;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
